name: Upsert OpenAI Assistant

on:
  push:
    branches:
      - fix_*

jobs:
  upsert-assistant:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get changed files in the docs folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v45
        env:
          LANG: en_US.UTF-8
          LC_ALL: C.UTF-8
