name: Upsert OpenAI Assistant

on:
  push:
    branches:
      - main
    paths:
      - upsert_scenario_path.txt
      - scenarios/**/setting.json
      - scenarios/**/instruction.txt

jobs:
  upsert-assistant:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get changed files in the docs folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v45

      - name: Run step if any file(s) in the docs folder change
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files-specific.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
